ALTER TABLE "Game" ADD COLUMN "variant" TEXT NOT NULL DEFAULT 'standard';
ALTER TABLE "Game" ADD COLUMN "whiteChecks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Game" ADD COLUMN "blackChecks" INTEGER NOT NULL DEFAULT 0;
